#!/bin/bash

rm -rf db/development.sqlite3
bundle exec rake db:migrate


wget 'https://docs.google.com/spreadsheet/pub?key=0AqHBdXx9vx3bdGl1eF9ycE40QUY2aUlNN1ZUMWpRT2c&output=csv' -O db/data/carousels.csv
bundle exec rake db:carousels
